name: lemonade_design_system
description: A Very Good Project created by Very Good CLI.
version: 0.8.0
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ^3.35.7

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf
          weight: 400
        - asset: assets/fonts/Figtree-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Figtree-Medium.ttf
          weight: 500
        - asset: assets/fonts/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Figtree-Bold.ttf
          weight: 700

  assets:
    - assets/svg/icons/
    - assets/svg/brandLogos/
    - assets/svg/flags/
