name: KMP Compilation check

on:
  push:
    branches: [ "master", "main" ]
    paths:
      - 'kmp/**'
  pull_request:
    branches: [ "master", "main" ]
    paths:
      - 'kmp/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle

      - name: Detekt
        run: ./gradlew detektMetadataCommonMain --no-daemon
        working-directory: ./kmp

      - name: Ktlint
        run: ./gradlew ktlintCheck --no-daemon
        working-directory: ./kmp

      - name: Build Project
        run: ./gradlew build --no-daemon
        working-directory: ./kmp
